version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PORT=5000
      # Uncomment and set these values for Telegram integration
      # - TELEGRAM_BOT_TOKEN=your_telegram_bot_token
      # - TELEGRAM_CHAT_ID=your_telegram_chat_id